language: php

php:
  - 7.2
  - 7.3

sudo: required

before_install:
  - sudo add-apt-repository ppa:libreoffice/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libreoffice unoconv
  - sudo mkdir ~/.config/libreoffice
  - sudo chmod 777 ~/.config/libreoffice

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit
