language: php

php:
  - 7.2
  - 7.3

sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libreoffice unoconv

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit
